services:
  - type: web
    name: twtheeq-auth
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: FIREBASE_API_KEY
        value: AIzaSyCumuEb5pKVwDGJDxU7YvPJs55q-YDHPHU
      - key: FIREBASE_AUTH_DOMAIN
        value: twtheeq-8785a.firebaseapp.com
      - key: FIREBASE_PROJECT_ID
        value: twtheeq-8785a
      - key: FIREBASE_STORAGE_BUCKET
        value: twtheeq-8785a.firebasestorage.app
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: "1015417316604"
      - key: FIREBASE_APP_ID
        value: 1:1015417316604:web:aa39dea41379dd1b372379
      - key: FIREBASE_DATABASE_URL
        value: https://twtheeq-8785a.firebaseio.com
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
